import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const extensionFiles = ['manifest.json', 'service-worker.js', 'content-script.js', 'lifecycle.js']
export const defaultExtensionDir = fileURLToPath(new URL('../extension/', import.meta.url))

export async function extensionBuild(extensionDir = defaultExtensionDir) {
  const hash = createHash('sha256')
  for (const file of extensionFiles) {
    const content = (await readFile(join(extensionDir, file), 'utf8')).replace(/\r\n/g, '\n')
    hash.update(`${file}\0${Buffer.byteLength(content)}\0`).update(content)
  }
  const buildId = hash.digest('hex')
  const manifest = JSON.parse(await readFile(join(extensionDir, 'manifest.json'), 'utf8'))
  if (!manifest.key) throw new Error('Fixed extension identity key is required')
  const identityHex = createHash('sha256').update(Buffer.from(manifest.key, 'base64')).digest('hex').slice(0, 32)
  const extensionId = [...identityHex].map((char) => String.fromCharCode(97 + parseInt(char, 16))).join('')
  return { buildId, extensionId, version: manifest.version }
}

export function buildInfoSource(buildId) {
  return `// Generated by scripts/extension-build.mjs; do not edit by hand.\nglobalThis.__sidecarBuildId = ${JSON.stringify(buildId)}\n`
}

export async function checkedExtensionBuild(extensionDir = defaultExtensionDir) {
  const build = await extensionBuild(extensionDir)
  const info = (await readFile(join(extensionDir, 'build-info.js'), 'utf8')).replace(/\r\n/g, '\n')
  if (info !== buildInfoSource(build.buildId)) throw new Error('Extension build-info is stale; run npm run extension:build before deployment')
  return build
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [action = '--print', ...extra] = process.argv.slice(2)
  if (extra.length || !['--print', '--write', '--check'].includes(action)) throw new Error('Usage: node scripts/extension-build.mjs [--print|--write|--check]')
  const build = await extensionBuild()
  if (action === '--write') await writeFile(join(defaultExtensionDir, 'build-info.js'), buildInfoSource(build.buildId), 'utf8')
  if (action === '--check') await checkedExtensionBuild()
  console.log(action === '--print' ? buildInfoSource(build.buildId).trimEnd() : JSON.stringify(build))
}
